### ISSUE TITLE
Request: Make release assets compatible with houseabsolute/ubi

### ISSUE THREAD

**Issue by AndydeCleyre** [libxmq/xmq#14]
The release assets, at least for Linux, are a little irregular in their naming and structure. This makes it hard to use various scripts and helpers for installing binaries from GitHub with this particular project.

One such helper is https://github.com/houseabsolute/ubi .

Can future releases make the "linux" part of the filename surrounded by word boundaries? That is, either `xmq-gnu-linux-release` or `xmq-linux-release`, rather than the current `xmq-gnulinux-release`?

And can the binary within be named `xmq`, with executable permissions set?

Thanks for this great project!

**Comment by AndydeCleyre** [comment]
Working perfectly, as tested with [mise](https://github.com/jdx/mise):

```console
$ mise use -g ubi:libxmq/xmq@latest
```

Thanks!

**Comment by weetmuts** [comment]
Great! I tried out mise myself. Very useful indeed!
